### ISSUE TITLE
small issue in output format

### ISSUE THREAD

**Issue by wwood** [ablab/viralVerify#1]
Hi,

I ran viralVerify with the `-p` flag, and most lines were fine, but I ran across one like this, where a comma seems to be missing from between the last two columns when there are no PFAMs detected:
```
cluster361_bin0_k105_8559,Uncertain - viral or bacterial,3643,-,--
```
Thanks, ben

**Comment by mikeraiko** [comment]
Thanks, misleading double dashes are fixed
