### ISSUE TITLE
Conda installable?

### ISSUE THREAD

**Issue by jolespin** [ablab/viralVerify#12]
I'd like to incorporate this in some conda environments.  RIght now I have some scripts that download it and add it to the path but it would be really convenient to have this installable via conda.  

Is this possible?

**Comment by mikeraiko** [comment]
Thanks for suggestion! I'm working on it - hope to make it available via conda in the next couple of weeks.

**Comment by jolespin** [comment]
Sounds good, I just saw this it's pip installable so that should work too. 

I had a couple of questions if you wouldn't mind: 
1. Can I use this on metaspades to pull out viral contigs (or would I need to run something like VirSorter2 or VirFinder)? 
2. How do I actually run metaviralspades? Is that included in the newest spades version?

**Comment by mikeraiko** [comment]
Sorry for delay.
Yes, you can use this on any set of contigs. The longer the better - the contig should contain enough "viral" proteins, whole isolated circular conitgs or long-read data are the best options.
