### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by sxh1136** [ablab/viralVerify#2]
Hi there,

I've been getting this error with one of my datasets:

`Gene prediction...
Traceback (most recent call last):
  File "/usr/local/software/viralVerify/viralverify.py", line 424, in <module>
    main()
  File "/usr/local/software/viralVerify/viralverify.py", line 220, in main
    if int(gene_start.strip()) < int((contig_len_circ[contig_name][0])):
ValueError: invalid literal for int() with base 10: '5_plasmid_pHL2708X3,_complete_sequence:0-8689:1_1'
`

This is what the that protein fasta looks like:

>NZ_CP021331.1_Maritalea_myrionectae_strain_HL2708#5_plasmid_pHL2708X3,_complete_sequence:0-8689:1_1 # 44 # 331 # 1 # ID=22686_1;partial=00;start_type=TTG;rbs_motif=GGA/GAG/AGG;rbs_spacer=5-10bp;gc_cont=0.462
MQKLPLDHVKIDKSFVQSADQDPRAHEITLTIVRLCSSFGMGCIAEGVETAAQLEMLSKI
GCHTLQGYYFAKPMSAKQVNQYIAENTPMISIGIG*

**Comment by mikeraiko** [comment]
Hi!
Can't reproduce, but the problem is definitely is in # in the plasmid name. 
I'll try to fix it anyway, for now you can just replace or remove the # symbol.
