### ISSUE TITLE
can viralVerify used for metatranscriptome?

### ISSUE THREAD

**Issue by microbiomeCat** [ablab/viralVerify#3]
Hi there,

I have learned that metaviralSPAdes was used for virus from metagenomes, but not very suitable for metatranscriptomes.

So can I use tools like Trinity or rnaSPAdes to first assemble the metatranscriptomes reads, and use viralVerify to find the viral contigs? Alse, dose viralComplete work for RNA viral contigs?

Thank you!

**Comment by mikeraiko** [comment]
Hi!
Yes, viralVerify can be used for metatranscriptomic data, it was trained on RNA viruses as well.
ViralComplete can be used for RNA viral contigs indeed, but you also may consider recently published tool checkV for this purpose.

**Comment by asl** [comment]
And to add here more: one could use rnaviralSPAdes from http://cab.spbu.ru/software/coronaspades/ to assemble RNA viruses for transcriptomes and metatranscriptomes (https://www.biorxiv.org/content/10.1101/2020.07.28.224584v1)

**Comment by microbiomeCat** [comment]
@mikeraiko  @asl That is great! And thanks for additional suggestions，that‘s really helpful to me.
