### ISSUE TITLE
disagreements between plasmidVerify and viralVerify

### ISSUE THREAD

**Issue by HaimAshk** [ablab/viralVerify#4]
Hi,

I have contigs assembled by plasmidSPAeds based on bacterial isolates PE reads -- therefore suspected plasmids. I want to further filter these contigs using plasmidVerify (as suggested in your paper) and viralVerify. So I have run both tools and found some disagreements in predictions. While, as expected, viralVerify predicted some of plasmidVerify 'Plasmid' contigs as viral ones, it also predicted some of the 'Chromosoome' plasmids as 'Plasmids'. 

For example here are predicted 'plasmids' by viralVerify:
```
NODE_15_length_37998_cov_14.724243_component_0,**Plasmid**,37998,-,6.89,AIRS AIRS_C MCPsignal 4HB_MCP_1 TarH Oxidored_FMN Peripla_BP_4 AP_endonuc_2 GFO_IDH_MocA GFO_IDH_MocA_C Sigma54_activat HTH_8 Radical_SAM Bac_luciferase BPD_transp_2 Acyl-CoA_dh_2 Acyl-CoA_dh_M Acyl-CoA_dh_N BPD_transp_2 ABC_tran ABC_tran ABC_tran LysR_substrate HTH_1 Acetyltransf_1 Sigma54_activat PAS_9 PAS PAS_4 HTH_8 PAS_9 PAS_8 PAS_8 Peripla_BP_4 Abhydrolase_1 CN_hydrolase Molybdopterin Molydop_binding BPD_transp_2 Acyl-CoA_dh_N Acyl-CoA_dh_2 Acyl-CoA_dh_M ABC_tran BCA_ABC_TP_C BPD_transp_2 AMP-binding VirK Pyr_redox_3 Peripla_BP_6
NODE_16_length_25536_cov_16.257905_component_0,**Plasmid**,25536,-,5.07,Fe-ADH adh_short_C2 adh_short adh_short_C2 Epimerase NAD_binding_9 DJ-1_PfpI HTH_18 DJ-1_PfpI Sigma54_activat XylR_N V4R HTH_8 LysR_substrate HTH_1 Phenol_MetA_deg Peripla_BP_6 DAO PALP OCD_Mu_crystall Shikimate_DH K_oxygenase LysE Beta-lactamase tRNA-synt_1g Cupin_2 Aldedh Phage_integrase
```
and the corresponding prediction by the plasmidVerify:
```
NODE_15_length_37998_cov_14.724243_component_0,**Chromosome**,-2.497141683569888,AIRS AIRS_C MCPsignal 4HB_MCP_1 TarH Oxidored_FMN Peripla_BP_4 AP_endonuc_2 GFO_IDH_MocA GFO_IDH_MocA_C Sigma54_activat HTH_8 Radical_SAM Bac_luciferase BPD_transp_2 Acyl-CoA_dh_2 Acyl-CoA_dh_M Acyl-CoA_dh_N BPD_transp_2 ABC_tran ABC_tran ABC_tran LysR_substrate HTH_1 Acetyltransf_1 Sigma54_activat PAS_9 PAS PAS_4 HTH_8 PAS_9 PAS_8 PAS_8 Peripla_BP_4 Abhydrolase_1 CN_hydrolase BPD_transp_2 Acyl-CoA_dh_N Acyl-CoA_dh_2 Acyl-CoA_dh_M ABC_tran BCA_ABC_TP_C Molybdopterin Molydop_binding BPD_transp_2 AMP-binding VirK Pyr_redox_3 Peripla_BP_6
NODE_16_length_25536_cov_16.257905_component_0,**Chromosome**,-3.574700563044223,Fe-ADH adh_short_C2 adh_short adh_short_C2 Epimerase NAD_binding_9 DJ-1_PfpI HTH_18 DJ-1_PfpI Sigma54_activat XylR_N V4R HTH_8 LysR_substrate HTH_1 Phenol_MetA_deg Peripla_BP_6 DAO PALP OCD_Mu_crystall Shikimate_DH K_oxygenase LysE Beta-lactamase tRNA-synt_1g Cupin_2 Aldedh Phage_integrase
```

I would be happy for your advice regarding the best strategy to continue. Should I look only on consensus prediction by both viralVerify and plasmidVerify (i.e. both tools predict them as a plasmid) or any other approach?

Thanks in advanced,
Haim

**Comment by mikeraiko** [comment]
Hi Haim!

Sorry for late reply. Indeed, we retrained our classifier in viralVerify, and results may differ slighltly. In your case it's hard to be certain - the scores in both cases are pretty low, and there are no strongly _plasmidic_ genes, such as replication proteins. 

Generally, it is advised to use viralVerify alone, and pay attention to reported plasmids with the low score (below 10) - these cases may require additional investigation.

Best,
Mike.
