### ISSUE TITLE
viralVerify vs plasmidVerify

### ISSUE THREAD

**Issue by RicardoGCCR** [ablab/viralVerify#9]
Hi ablab, 
Thanks for your tools! 
I have a couple of questions> 
1. Is plasmidVerify integrated in viralVerify? will be any difference if I run the two tools to my contigs or will that be redundant?
2.  How can I interpret the scores I am getting from viralverify? and biological threshold behind?
Thanks!
Ricardo

**Comment by mikeraiko** [comment]
Dear Ricardo,

1.Yes, it's now integrated in viralVerify. Just run it with -p flag, and you'll get plasmid prediction results along with viral and chromosomal contigs. So, you need only one tool.

2. To put it simply, it's a difference between probabilities of being chromosomal or plasmid for each contig, based on gene content. Higher positive score means higher probability for the contig to be a plasmid, and vice versa. Score near zero means "uncertain"  - there is no known "plasmid-specific" or "chromosome-specific" genes, and it needs additional examination.
